### ISSUE TITLE
Allow customize localEndpoint.serviceName

### ISSUE THREAD

**Issue by carnei-ro** [Kong/kong-plugin-zipkin#110]
I have a lot of kong clusters. The plugin (version 1.2.0) has the localEndpoint.serviceName hard-coded as "kong", making it difficult to understand which "kong cluster" handled the request.
So far, I forked and coded the plugin to let me customize the tag `lc` (component). I think the `serviceName` would be better tho.

**Comment by kikito** [comment]
Custom tags can be added via the `static_tags` config option. Example declarative config:

```
plugins:
  name: zipkin
  ...
  static_tags:
    - name: kong-instance-name
      value: kong-production-1
```
Will add a tag called kong-instance-name with value kong-production-1 to all the request tags.

It is not possible to use this feature in order to override the default tags (such as `lc`, which will always have the value kong), but you should be able to filter traces using a different tag.

I hope this compromise is acceptable.
