### ISSUE TITLE
Way to disable tracing on specific routes?

### ISSUE THREAD

**Issue by bforbis** [Kong/kong-plugin-zipkin#120]
I currently want tracing to be enabled for all routes except for some specific routes that are extremely noisy. If I was to do this given the current configuration option, I would have to enumerate all routes and configure this plugin except for the one route that I want zipkin disabled on. This ends up being a ton of configuration.

Instead, I would like to configure zipkin globally, but add in a small config list of matched routes to disable tracing on.

Example with db-less config:
```
services:
  - name: foo
     url: foo.com
     routes:
       - /foo
```
